'use client';

import React from 'react';
import PageHeader from '@/components/shared/PageHeader';
import LoadingSpinner from '@/components/shared/LoadingSpinner';
import { useNotifications } from '@/lib/hooks/useNotifications';
import { formatDate } from '@/lib/utils';
import { Bell, Check, UserCheck, MessageSquare, Trash2 } from 'lucide-react';

export default function AdminNotificationsPage() {
  const { notifications, unreadCount, markAllAsRead, markAsRead, isLoading } = useNotifications();

  const getIcon = (type: string) => {
    switch (type) {
      case 'new_user':
        return <UserCheck className="h-5 w-5 text-emerald-500" />;
      case 'task_completed':
        return <Check className="h-5 w-5 text-indigo-500" />;
      case 'new_comment':
        return <MessageSquare className="h-5 w-5 text-violet-500" />;
      default:
        return <Bell className="h-5 w-5 text-muted-foreground" />;
    }
  };

  const getBgColor = (type: string, isRead: boolean) => {
    if (isRead) return 'bg-muted/10 border-border/40';
    switch (type) {
      case 'new_user':
        return 'bg-emerald-500/5 border-emerald-500/10';
      case 'task_completed':
        return 'bg-indigo-500/5 border-indigo-500/10';
      case 'new_comment':
        return 'bg-violet-500/5 border-violet-500/10';
      default:
        return 'bg-primary/5 border-primary/10';
    }
  };

  return (
    <div className="space-y-6">
      <PageHeader
        title="Admin Notifications"
        description="Review recent logs and event alerts generated by system activities."
        action={
          unreadCount > 0 && (
            <button
              onClick={() => markAllAsRead()}
              className="px-4 py-2 text-xs font-semibold rounded-xl bg-primary/15 hover:bg-primary/20 text-primary border border-primary/25 transition-all"
            >
              Mark All as Read
            </button>
          )
        }
      />

      {isLoading ? (
        <LoadingSpinner size="lg" className="h-[50vh]" />
      ) : notifications.length === 0 ? (
        <div className="text-center py-12 border rounded-2xl border-dashed border-border/80 bg-card/10">
          <Bell className="h-10 w-10 text-muted-foreground/60 mx-auto mb-3" />
          <p className="text-sm text-muted-foreground">You have no notification logs.</p>
        </div>
      ) : (
        <div className="space-y-3.5">
          {notifications.map((notification) => (
            <div
              key={notification._id}
              onClick={() => !notification.isRead && markAsRead(notification._id)}
              className={`flex items-start justify-between p-4.5 rounded-2xl border transition-all duration-200 cursor-pointer ${getBgColor(
                notification.type,
                notification.isRead
              )}`}
            >
              <div className="flex space-x-3.5">
                {/* Visual Icon Box */}
                <div className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-card border border-border/60 shadow-sm`}>
                  {getIcon(notification.type)}
                </div>
                
                {/* Msg text */}
                <div>
                  <p className={`text-sm text-foreground leading-normal ${!notification.isRead ? 'font-semibold' : 'font-medium'}`}>
                    {notification.message}
                  </p>
                  <p className="text-[10px] text-muted-foreground mt-1">
                    {formatDate(notification.createdAt, 'PPpp')}
                  </p>
                </div>
              </div>

              {/* Status Indicator circle */}
              {!notification.isRead && (
                <div className="h-2 w-2 rounded-full bg-primary mt-2" title="Unread" />
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
